Initial implementation of BLS signatures
dusk-network/bls12-381-sig pull request #2
Opened 2020-10-21 10:24 UTC by julesdesmit

Fixes #1

2020-10-21 15:46 UTC, vlopes11 requested changes
Few nits

2020-10-21 15:46 UTC, vlopes11 commented on src/hash.rs
> +    let mut hasher = Blake2s::new();
Why not Blake3?

2020-10-21 15:46 UTC, vlopes11 commented on src/hash.rs
> +    let mut arr = [0u8; 32];
`Output::into_bytes` already provide a 32 bytes array. Why the extra copy?

2020-10-21 15:46 UTC, vlopes11 commented on src/hash.rs
> +    arr[31] &= 0b0011_1111;
I believe we should rely on the API from `dusk_plonk::prelude::BlsScalar::from_bytes` instead of clamping the bits manually.

We have all the cases covered there including the subtraction of the module and the Montgomery reduction.

2020-10-21 15:46 UTC, vlopes11 commented on src/hash.rs
> +    let scalar = BlsScalar::from_bytes(&arr).unwrap();
We can't unwrap here since it is error prone. If we cannot suffer failure in this function, we should produce a hash with 512 bits and use `from_bytes_wide` of `BlsScalar`

2020-10-21 15:46 UTC, vlopes11 commented on src/hash.rs
> +    let mut arr = [0u8; 32];
Same as above

2020-10-21 15:46 UTC, vlopes11 commented on src/hash.rs
> +    arr[31] &= 0b0011_1111;
Same as above

2020-10-21 15:47 UTC, julesdesmit commented on src/hash.rs
> +    let mut arr = [0u8; 32];
Good catch, I wasn't aware of that functionality.

2020-10-21 15:49 UTC, julesdesmit commented on src/hash.rs
> +    let mut hasher = Blake2s::new();
I wasn't actually aware of its existence. I will swap it.

2020-10-21 15:51 UTC, julesdesmit commented on src/hash.rs
> +    arr[31] &= 0b0011_1111;
Isn't that the exact same function? Or am I missing something

2020-10-21 15:57 UTC, julesdesmit commented on src/hash.rs
> +    let scalar = BlsScalar::from_bytes(&arr).unwrap();
If we swap to Blake3 we will not be able to produce a 512 bit hash, will we? It seems it's fixed on 256 bits.

2020-10-21 17:26 UTC, vlopes11 approved these changes
LGTM, good job

2020-10-22 12:12 UTC, ZER0 requested changes
Overall looks good. Just some minor implementation changes, and API changes.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +fn unsafe_sign_verify_incorrect_message() {
Same as above for the `unsafe_` prefix.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let pk = PublicKey::new(&sk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +fn unsafe_sign_verify_incorrect_pk() {
Same as above for the `unsafe_` prefix

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let pk = PublicKey::new(&sk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let pk = PublicKey::new(&sk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let apk = APK::new(&pk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let pk = PublicKey::new(&sk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let apk = APK::new(&pk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let pk = PublicKey::new(&sk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let pk = PublicKey::new(&sk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let apk = APK::new(&pk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let pk = PublicKey::new(&sk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let mut apk = APK::new(&pk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +        let pk = PublicKey::new(&sk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let pk = PublicKey::new(&sk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let mut apk = APK::new(&pk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    (0..10).for_each(|_| {
you can use a regular `for` loop here, it's probably more readable.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +        let pk = PublicKey::new(&sk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let pk = PublicKey::new(&sk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let mut apk = APK::new(&pk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    (0..10).for_each(|_| {
you can use a regular `for` loop here, it's probably more readable.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +        let pk = PublicKey::new(&sk);
Same as above for generation / conversion.

2020-10-22 12:12 UTC, ZER0 commented on tests/tests.rs
> +    let apk = APK::new(&pk);
Same as above for generation / conversion.

2020-10-22 13:24 UTC, ZER0 approved these changes
LGTM, just change the name of the crates as discussed (I will change the name of the repo)

We might want to add also in the future the generator method for consistency, as briefly mentioned in the last review (e.g. `sk.public_key()`) but it's not mandatory to do it now and can be done later on.

2020-10-22 13:24 UTC, ZER0 commented on Cargo.toml
> +name = "bls12-381-sig"
You can probably already rename it to `bls12_381-sign` as discussed; or maybe `dusk-bls12_381-sign` since our bls crates has prefix dusk, and this is looks like strictly related.

I will take care of the repo name.

2020-10-22 13:34 UTC, merged